### PR TITLE
Fix Home Manager module package default

### LINKED ISSUE #309: Failure to use homeManagerModule
**Describe the bug**
When I try to use and import the `homeManagerModule` I get an error

**To Reproduce**
1. import `emanote.homeManageModule`
2. Try to build
3. See error

**Expected behavior**
No error

**Additional context**

Here's the error message:

```
error: attribute 'emanote' missing

at /nix/store/ibdwi8msnjcljwv9j6xzf55azxkggki7-source/nix/home-manager-module.nix:39:19:

38|         type = types.package;
39|         default = pkgs.emanote;
|                   ^
40|         defaultText = "pkgs.emanote";
Did you mean one of emote or remnote?
(use '--show-trace' to show detailed location information)
```

### PR DESCRIPTION
**Pull request by srid**
**`emanote.homeManagerModule` now works without a manual package override**, fixing the failure reported in #309. The flake-level Home Manager export supplies Emanote's own default package, while the reusable module keeps its plain `pkgs.emanote` default for non-flake imports.

The regression is covered by a Linux NixOS VM test flake under `nix/home-manager-test`. It imports `emanote.homeManagerModule`, enables the user service without setting `services.emanote.package`, waits for `emanote.service`, and confirms the local HTTP server responds. *Vira builds this test flake directly and overrides its `emanote` input to the checked-out PR tree.*

### Notable details

- The root flake does not gain a Home Manager input.
- Home Manager is pinned only inside the standalone test flake and follows Emanote's `nixpkgs`.
- `vira.hs` now builds both the root flake and `./nix/home-manager-test`.
- The Nix install docs now show `package = ...` as an optional override rather than a required workaround.

### Verification

```sh
nix develop -c cabal build all
just fmt
nix build -L ./nix/home-manager-test --override-input emanote . --no-link
```

Closes #309.

### Try it locally

```sh
nix build 'github:srid/emanote/fix-home-manager-module-vm-test?dir=nix/home-manager-test' \
  --override-input emanote github:srid/emanote/fix-home-manager-module-vm-test
```

_Generated by [`/do`](https://github.com/srid/agency) on Codex (model `gpt-5`)._

### CODE REVIEW

**Comment by srid** [comment]
## [Hickey/Lowy](https://kolu.dev/blog/hickey-lowy/) Analysis

| # | Reviewer | Finding | Disposition |
| --- | --- | --- | --- |
| 1 | Hickey | Package default policy was fragmented between the generic Home Manager module and the flake export. | Fixed in `9292ab48`: the flake wrapper now supplies the self-backed default with `lib.mkDefault`, while the generic module keeps its `pkgs.emanote` default. |
| 2 | Lowy | The package source leaked into the lower-level Home Manager module instead of staying at the flake boundary. | No separate change: this was subsumed by the Hickey fix in `9292ab48`. |

The resulting boundary is intentionally narrow: direct imports of `nix/modules/home/emanote.nix` keep the old nixpkgs-oriented behavior, while `emanote.homeManagerModule` carries the flake-specific package default needed by issue #309.

**Comment by srid** [comment]
## `/do` Results

| Step | Status | Duration | Verification |
|------|--------|----------|--------------|
| sync | passed | 1s | git fetch ok; forge=github; noGit=false |
| research | passed | 5m 46s | Issue #309 traced to `nix/modules/home/emanote.nix` defaulting to `pkgs.emanote`; planned self-backed module default plus Linux VM check. |
| branch | passed | 4s | Created `fix-home-manager-module-vm-test` from `origin/master`. |
| implement | passed | 13m 18s | Added self-backed `homeManagerModule` default, Linux VM check, and explicit root flake in `vira.hs`; VM check built successfully. |
| check | passed | 43s | `nix develop -c cabal build all` passed. |
| docs | passed | 26s | Updated Nix install docs and changelog. |
| fmt | passed | 10s | `just fmt` passed. |
| commit | passed | 57s | Created and pushed feature/docs commits. |
| hickey+lowy | passed | 5m 25s | Fixed shared package-default boundary finding in `9292ab48`; Lowy finding was subsumed by the same fix. |
| police | passed | 3m 8s | Fixed missing release-check rationale comment; rules, fact-check, and elegance were clean afterward. |
| test | passed | 6s | `nix build -L .#checks.x86_64-linux.home-manager-module --no-link` passed. |
| create-pr | passed | 38s | Created draft PR #685 and posted Hickey/Lowy analysis. |
| ci | passed | 3m 31s | `vira ci` passed; signed off `vira/aarch64-darwin` and `vira/x86_64-linux`. |
| evidence | passed | 0s | No visible UI impact; PR evidence not required. |
| **Total** |  | **36m 22s** |  |

**Slowest step:** `implement` at 13m 18s.

### Process notes

The expensive part was iterating the VM service probe. Future NixOS VM tests like this should start with a bounded HTTP probe (`curl --max-time`) and an explicit user-systemd environment when checking user services from the test driver.

File: vira.hs [hunk 1]
```diff
@@ -3,6 +3,7 @@
   let isMaster = ctx.branch == "master"
   in pipeline
     { build.systems = [ "x86_64-linux", "aarch64-darwin" ]
+    , build.flakes = [ "." ]
```
Comment (srid) [inline vira.hs]: wtf, add the home-manager-test.nix itself (and that should be a directory with flake.nix) per https://vira.nixos.asia/config

Comment (srid) [reply vira.hs]: Addressed in `49b5509e` and `6dd493b0`.

`nix/home-manager-test` is now a standalone flake with its own `flake.nix`, and `vira.hs` builds both `.` and `./nix/home-manager-test`. Vira overrides the test flake `emanote` input to `.` so it tests the checked-out PR tree instead of the default upstream input.

Verified locally:

```sh
just fmt
nix build -L .#checks.x86_64-linux.home-manager-module --no-link
nix build -L ./nix/home-manager-test --override-input emanote . --no-link
vira ci
```

`vira ci` passed and signed off `vira/aarch64-darwin` and `vira/x86_64-linux` on `6dd493b0`.
